# Generated by Django 3.1.7 on 2021-05-14 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_num', models.IntegerField(unique=True)),
                ('user_name', models.CharField(max_length=120, unique=True)),
                ('balance', models.IntegerField(default=0)),
                ('acnt_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_acno', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('acccount_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.accountdetails')),
            ],
        ),
    ]
