# Generated by Django 3.1.7 on 2021-05-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20210514_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='acccount_num',
            new_name='account_num',
        ),
    ]
